---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: dev
  name: webserver
  labels:
    app: webserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: mywebserver
        image: 10.100.0.174:5000/leeyj7141/centos-httpd:19
        ports:
          - containerPort: 80
