---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    strategy.spinnaker.io/max-version-history: '3'
    traffic.spinnaker.io/load-balancers: '["service webserver-service"]' 
  labels:
    tier: webserver
  name: webserver
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: webserver
  template:
    metadata:
      labels:
        tier: webserver
    spec:
      containers:
        - image: 10.100.0.174:5000/leeyj7141/centos-httpd:73
          name: webserver
          ports:
            - containerPort: 80

